// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
  ],
  firebase: {
    apiKey: 'AIzaSyAqyO4iw8hbPZbQ5qeG3c67uOQkkKoSVDA',
    authDomain: 'configure-live.firebaseapp.com',
    databaseURL: 'https://configure-live.firebaseio.com',
    projectId: 'configure-live',
    storageBucket: 'configure-live.appspot.com',
    messagingSenderId: '471593344960'
  }
};
